openapi: 3.0.0
info:
  title: SimpleWeather API
  description: Open-Meteo és Geocoding API hívások a SimpleWeather alkalmazáshoz
  version: "1.0"

servers:
  - url: https://api.open-meteo.com
    description: Open-Meteo időjárás API
  - url: https://geocoding-api.open-meteo.com
    description: Open-Meteo geokódoló API

paths:
  /v1/forecast:
    get:
      summary: Időjárás előrejelzés lekérése
      parameters:
        - name: latitude
          in: query
          required: true
          schema:
            type: number
        - name: longitude
          in: query
          required: true
          schema:
            type: number
        - name: daily
          in: query
          required: true
          schema:
            type: string
        - name: hourly
          in: query
          required: true
          schema:
            type: string
        - name: timezone
          in: query
          required: true
          schema:
            type: string
        - name: forecast_days
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Sikeres válasz az időjárás előrejelzéssel
  /v1/search:
    get:
      summary: Helyszín keresés név alapján
      parameters:
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: count
          in: query
          required: false
          schema:
            type: integer
        - name: language
          in: query
          required: false
          schema:
            type: string
        - name: format
          in: query
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Sikeres helyszín keresési válasz
